// User Authentication
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Game Reducer
// PlayerHealthArmor and BATTLE NUMBER
export const SET_PLAYER_HEALTH_ARMOR = "SET_PLAYER_HEALTH_ARMOR";
export const SET_PLAYER_TOTAL_ARMOR = "SET_PLAYER_TOTAL_ARMOR";
export const SET_PLAYER_TOTAL_HEALTH = "SET_PLAYER_TOTAL_HEALTH";
export const SET_BATTLE_NUMBER = "SET_BATTLE_NUMBER";
export const RESET_BATTLE_NUMBER = "RESET_BATTLE_NUMBER";
export const SET_PLAYER_ANIMATION = "SET_PLAYER_ANIMATION";
export const SET_PLAYER_SPRITE = "SET_PLAYER_SPRITE";
// MONSTERHealthArmor
export const SET_MONSTER = "SET_MONSTER";
export const SET_ALL_MONSTERS = "SET_ALL_MONSTERS";
export const SET_MONSTER_ANIMATION = "SET_MONSTER_ANIMATION";
export const SET_MONSTER_SPRITE = "SET_MONSTER_SPRITE";
// Cards
export const SET_CARDS = "SET_CARDS";